server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: socket-service
  jpa:
  database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  show-sql: true
  generate-ddl: false
  hibernate:
    #         dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    ddl-auto: none
    default_schema: ludo_db
  datasource:
    url: jdbc:mysql://0.0.0.0:3307/ludo_db?enabledTLSProtocols=TLSv1.2
    username: demo
    password: demo
    driver-class-name: com.mysql.cj.jdbc.Driver